/*
Loops OpenAPI Spec

This is the OpenAPI Spec for the [Loops API](https://loops.so/docs/api).

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loops

import (
	"encoding/json"
)

// checks if the TransactionalFailureResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransactionalFailureResponse{}

// TransactionalFailureResponse struct for TransactionalFailureResponse
type TransactionalFailureResponse struct {
	Success *bool `json:"success,omitempty"`
	Path *string `json:"path,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewTransactionalFailureResponse instantiates a new TransactionalFailureResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionalFailureResponse() *TransactionalFailureResponse {
	this := TransactionalFailureResponse{}
	return &this
}

// NewTransactionalFailureResponseWithDefaults instantiates a new TransactionalFailureResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionalFailureResponseWithDefaults() *TransactionalFailureResponse {
	this := TransactionalFailureResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *TransactionalFailureResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionalFailureResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *TransactionalFailureResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *TransactionalFailureResponse) SetSuccess(v bool) {
	o.Success = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *TransactionalFailureResponse) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionalFailureResponse) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *TransactionalFailureResponse) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *TransactionalFailureResponse) SetPath(v string) {
	o.Path = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *TransactionalFailureResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionalFailureResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *TransactionalFailureResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *TransactionalFailureResponse) SetMessage(v string) {
	o.Message = &v
}

func (o TransactionalFailureResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransactionalFailureResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableTransactionalFailureResponse struct {
	value *TransactionalFailureResponse
	isSet bool
}

func (v NullableTransactionalFailureResponse) Get() *TransactionalFailureResponse {
	return v.value
}

func (v *NullableTransactionalFailureResponse) Set(val *TransactionalFailureResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionalFailureResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionalFailureResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionalFailureResponse(val *TransactionalFailureResponse) *NullableTransactionalFailureResponse {
	return &NullableTransactionalFailureResponse{value: val, isSet: true}
}

func (v NullableTransactionalFailureResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionalFailureResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


