/*
Loops OpenAPI Spec

This is the OpenAPI Spec for the [Loops API](https://loops.so/docs/api).

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loops

import (
	"encoding/json"
)

// checks if the ContactSuccessResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContactSuccessResponse{}

// ContactSuccessResponse struct for ContactSuccessResponse
type ContactSuccessResponse struct {
	Success *bool `json:"success,omitempty"`
	Id *string `json:"id,omitempty"`
}

// NewContactSuccessResponse instantiates a new ContactSuccessResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContactSuccessResponse() *ContactSuccessResponse {
	this := ContactSuccessResponse{}
	return &this
}

// NewContactSuccessResponseWithDefaults instantiates a new ContactSuccessResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContactSuccessResponseWithDefaults() *ContactSuccessResponse {
	this := ContactSuccessResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *ContactSuccessResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContactSuccessResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *ContactSuccessResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *ContactSuccessResponse) SetSuccess(v bool) {
	o.Success = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ContactSuccessResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ContactSuccessResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ContactSuccessResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ContactSuccessResponse) SetId(v string) {
	o.Id = &v
}

func (o ContactSuccessResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContactSuccessResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableContactSuccessResponse struct {
	value *ContactSuccessResponse
	isSet bool
}

func (v NullableContactSuccessResponse) Get() *ContactSuccessResponse {
	return v.value
}

func (v *NullableContactSuccessResponse) Set(val *ContactSuccessResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableContactSuccessResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableContactSuccessResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContactSuccessResponse(val *ContactSuccessResponse) *NullableContactSuccessResponse {
	return &NullableContactSuccessResponse{value: val, isSet: true}
}

func (v NullableContactSuccessResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContactSuccessResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


