/*
Loops OpenAPI Spec

This is the OpenAPI Spec for the [Loops API](https://loops.so/docs/api).

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package loops

import (
	"encoding/json"
)

// checks if the TransactionalFailure2Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransactionalFailure2Response{}

// TransactionalFailure2Response struct for TransactionalFailure2Response
type TransactionalFailure2Response struct {
	Success *bool `json:"success,omitempty"`
	Error *TransactionalFailure2ResponseError `json:"error,omitempty"`
}

// NewTransactionalFailure2Response instantiates a new TransactionalFailure2Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionalFailure2Response() *TransactionalFailure2Response {
	this := TransactionalFailure2Response{}
	return &this
}

// NewTransactionalFailure2ResponseWithDefaults instantiates a new TransactionalFailure2Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionalFailure2ResponseWithDefaults() *TransactionalFailure2Response {
	this := TransactionalFailure2Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *TransactionalFailure2Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionalFailure2Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *TransactionalFailure2Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *TransactionalFailure2Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *TransactionalFailure2Response) GetError() TransactionalFailure2ResponseError {
	if o == nil || IsNil(o.Error) {
		var ret TransactionalFailure2ResponseError
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionalFailure2Response) GetErrorOk() (*TransactionalFailure2ResponseError, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *TransactionalFailure2Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given TransactionalFailure2ResponseError and assigns it to the Error field.
func (o *TransactionalFailure2Response) SetError(v TransactionalFailure2ResponseError) {
	o.Error = &v
}

func (o TransactionalFailure2Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransactionalFailure2Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableTransactionalFailure2Response struct {
	value *TransactionalFailure2Response
	isSet bool
}

func (v NullableTransactionalFailure2Response) Get() *TransactionalFailure2Response {
	return v.value
}

func (v *NullableTransactionalFailure2Response) Set(val *TransactionalFailure2Response) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionalFailure2Response) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionalFailure2Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionalFailure2Response(val *TransactionalFailure2Response) *NullableTransactionalFailure2Response {
	return &NullableTransactionalFailure2Response{value: val, isSet: true}
}

func (v NullableTransactionalFailure2Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionalFailure2Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


